# Generated by Django 4.0.4 on 2022-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_alter_blog_date_created_alter_blog_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.IntegerField(choices=[(1, 'ຂ່າວປະກາດ'), (2, 'ໂຄສະນາ'), (3, 'ບັນທຶກ')], default=1),
        ),
    ]
